name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore music-debug.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias debug \
            -storepass "@JUsT7TEENAKC" \
            -keypass "@JUsT7TEENAKC" \
            -dname "CN=Aman, OU=Dev, O=MajdoorAI, L=City, S=State, C=IN"

      - name: Encode to base64
        run: base64 -w 0 music-debug.jks > keystore_base64.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            music-debug.jks
            keystore_base64.txt
